/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DateTimePicker: typeof import('./src/components/DateTimePicker.vue')['default']
    Drain: typeof import('./src/components/Drain.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Star: typeof import('./src/components/Star.vue')['default']
    Tick: typeof import('./src/components/Tick.vue')['default']
  }
}
